# Generated by Django 3.2.5 on 2021-08-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McnMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50, unique=True, verbose_name='机器名称')),
                ('machine_host', models.GenericIPAddressField(default='127.0.0.1', verbose_name='机器地址')),
            ],
            options={
                'verbose_name': '机器列表',
                'verbose_name_plural': '机器列表',
                'db_table': 'mcn_machine',
                'unique_together': {('machine_host',)},
            },
        ),
        migrations.CreateModel(
            name='McnSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_identity', models.CharField(max_length=20, verbose_name='同步标识')),
                ('sync_name', models.CharField(max_length=20, unique=True, verbose_name='同步名称')),
                ('sync_url', models.URLField(max_length=250, verbose_name='同步地址')),
                ('sync_limit', models.IntegerField(default=1000, verbose_name='同步数量/次')),
                ('sync_type', models.SmallIntegerField(choices=[(0, '未知'), (1, '审核'), (2, '快速'), (3, '正常')], default=0, help_text='0未知/1审核/2快速/3正常', verbose_name='同步类型')),
                ('sync_active', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, help_text='0否/1是', verbose_name='是否开启同步')),
            ],
            options={
                'verbose_name': '同步列表',
                'verbose_name_plural': '同步列表',
                'db_table': 'mcn_sync',
                'unique_together': {('sync_identity', 'sync_url')},
            },
        ),
        migrations.CreateModel(
            name='McnPlat',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='平台ID')),
                ('plat_identity', models.CharField(max_length=20, verbose_name='平台标识')),
                ('plat_name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('clear_active', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否清除队列')),
            ],
            options={
                'verbose_name': '平台列表',
                'verbose_name_plural': '平台列表',
                'db_table': 'mcn_plat',
                'unique_together': {('plat_identity', 'plat_name')},
            },
        ),
        migrations.CreateModel(
            name='McnAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_identity', models.CharField(max_length=50, verbose_name='账号标识')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='账号名称')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='账号密码')),
                ('cookies', models.TextField(blank=True, default='{}', verbose_name='账号缓存')),
                ('mcn_plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.mcnplat', verbose_name='平台ID')),
            ],
            options={
                'verbose_name': '账户列表',
                'verbose_name_plural': '账户列表',
                'db_table': 'mcn_account',
                'unique_together': {('mcn_plat', 'account_identity', 'username')},
            },
        ),
        migrations.CreateModel(
            name='McnRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.SmallIntegerField(choices=[(0, '停用'), (1, '启用')], default=1, verbose_name='是否启用运行')),
                ('mcn_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.mcnaccount', verbose_name='账户ID')),
                ('mcn_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.mcnmachine', verbose_name='机器ID')),
            ],
            options={
                'verbose_name': '运行列表',
                'verbose_name_plural': '运行列表',
                'db_table': 'mcn_run',
                'unique_together': {('mcn_machine', 'mcn_account')},
            },
        ),
    ]
