"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from __future__ import absolute_import, unicode_literals
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7g^k3a9(6@7^cfauqbxtg4p^w2t8fy%2kgc#y89y706sl!@6#h'

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = False
=======
DEBUG = True
>>>>>>> be578f62a7c006f841af731d40f2ab57ac4e461e

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'custom.apps.CustomConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dashboard',
        'USER': 'root',
        'PASSWORD': 'root',
        # 'HOST': '127.0.0.1',
        'HOST': 'mariadb',  # ! docker用
        'POST': 3306,
    }
}
# ! 新版本增加
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'
<<<<<<< HEAD
STATIC_ROOT = 'static'
=======
# STATIC_ROOT = 'static'
>>>>>>> be578f62a7c006f841af731d40f2ab57ac4e461e


# SimpleUI Setup
SIMPLEUI_INDEX = '#'  # 设置点击首页图标跳转的地址
SIMPLEUI_DEFAULT_THEME = 'layui.css'
SIMPLEUI_HOME_INFO = False 
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_DEFAULT_ICON = False
SIMPLEUI_LOGO = '/static/tiandi.png'  # 自定义Logo
SIMPLEUI_STATIC_OFFLINE = True  # 指定simpleui 是否以脱机模式加载静态资源

# # 修改左侧菜单首页设置
# SIMPLEUI_HOME_TITLE = 'Astar欢迎你!'  # 首页标题
# SIMPLEUI_HOME_ICON = 'fas fa-tachometer-alt'  # 首页图标
# SIMPLEUI_HOME_PAGE = '/custom/overview/'  # 指向页面



# 自定义菜单 图标设置，图标参考： https://fontawesome.com/icons?d=gallery
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 在自定义菜单的基础上保留系统模块
    'dynamic': True,
    'menu_display': ['数据分析'],
    'menus': [
        {'app': 'auth', 'name': '权限认证', 'icon': 'fas fa-user-shield', 
         'models': [
             {'name': '用户', 'icon': 'fas fa-user', 'url': 'auth/user/'}, 
             {'name': '组', 'icon': 'fas fa-users-cog', 'url': 'auth/group/'}, 
             ]
         },
        {'app': 'analysis', 'name': '数据分析', 'icon': 'fab fa-connectdevelop', 
         'models': [
            {'name': '概览分析', 'icon': 'fas fa-chart-bar', 'url': '/custom/overview/'},
            {'name': '行业分析', 'icon': 'fas fa-chart-line', 'url': '/custom/industry/'},
            {'name': '平台分析', 'icon': 'fas fa-chart-pie', 'url': '/custom/platform/'},
            {'name': '媒介分析', 'icon': 'fas fa-chart-area', 'url': '/custom/medium/'},
             ]
         },

        # {'app': 'beat', 'name': '任务管理', 'icon': 'fas fa-kiss-wink-heart',
        # 'models': [
        #     {'name': '结果列表', 'icon': 'fas fa-mug-hot', 'url': 'beat/mcnresult/'},
        #     {'name': '任务运行', 'icon': 'fas fa-business-time', 'url': 'beat/periodictask/'},
        #     {'name': '时间间隔', 'icon': 'fas fa-stopwatch', 'url': 'beat/intervalschedule/'},
        #     {'name': '日期定时', 'icon': 'fas fa-clock', 'url': 'beat/clockedschedule/'},
        #     {'name': '计划任务', 'icon': 'far fa-calendar-alt', 'url': 'beat/crontabschedule/'},
        #     {'name': '日照事件', 'icon': 'fas fa-sun', 'url': 'beat/solarschedule/'},
        # ]}
        ]
}


